#!C:\Users\harsh\Desktop\My space\Projects 2025\DL-Image-Classification-MLFlow-DVC\dlprojvenv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
